import {
  collection, doc, addDoc, updateDoc, setDoc, query, where,
  orderBy, onSnapshot, serverTimestamp, Timestamp, increment,
  writeBatch, getDocs, getDoc, arrayUnion, limit
} from "firebase/firestore";
import { db } from "@/lib/firebase/client";

export interface ConversationData {
  id: string;
  participants: string[];
  participantNames: Record<string, string>;
  participantPhotos: Record<string, string>;
  type: "direct" | "group";
  groupName?: string;
  groupPhotoUrl?: string;
  groupDescription?: string;
  createdBy?: string;
  createdAt?: Timestamp;
  admins?: string[];
  eventId?: string;
  committeeId?: string;
  autoGenerated?: boolean;
  lastMessage: string;
  lastMessageSenderId: string;
  updatedAt?: Timestamp;
  unreadCount: Record<string, number>;
  blockedBy?: string[];
}

export interface MessageData {
  id: string;
  senderId: string;
  senderName: string;
  text: string;
  timestamp?: Timestamp;
  readBy: string[];
  readAt?: Record<string, Timestamp>;
  systemMessage?: boolean;
  status?: "sending" | "sent" | "failed";
}

export function getUserConversations(
  uid: string,
  callback: (conversations: ConversationData[]) => void
): () => void {
  const ref = collection(db, "conversations");
  const q = query(ref, where("participants", "array-contains", uid), orderBy("updatedAt", "desc"));
  return onSnapshot(q, snap => {
    callback(snap.docs.map(d => ({ id: d.id, ...d.data() } as ConversationData)));
  });
}

// Fixed: getConversationMessages now supports pagination (using a cursor in ChatWindow)
// We provide a function that returns a query we can paginate, but for realtime we need to be careful.
// Standard onSnapshot on the last N messages:
export function getConversationMessagesRealtime(
  conversationId: string,
  limitCount: number,
  callback: (messages: MessageData[]) => void
): () => void {
  const ref = collection(db, "conversations", conversationId, "messages");
  const q = query(ref, orderBy("timestamp", "desc"), limit(limitCount));
  return onSnapshot(q, snap => {
    // Reverse because we want oldest first in the UI, but queried desc to get latest N
    const msgs = snap.docs.map(d => ({ id: d.id, ...d.data() } as MessageData)).reverse();
    callback(msgs);
  });
}

export async function sendMessage(
  conversationId: string,
  senderId: string,
  senderName: string,
  text: string,
  initialConvData?: Partial<ConversationData>
): Promise<void> {
  const convRef = doc(db, "conversations", conversationId);
  const convSnap = await getDoc(convRef);
  
  if (!convSnap.exists()) {
    if (initialConvData) {
      await setDoc(convRef, {
        ...initialConvData,
        lastMessage: text,
        lastMessageSenderId: senderId,
        updatedAt: serverTimestamp(),
      });
    } else {
      // Fallback for missing initial data (shouldn't happen with new flow)
      await setDoc(convRef, {
        participants: [senderId],
        type: "direct",
        lastMessage: text,
        lastMessageSenderId: senderId,
        updatedAt: serverTimestamp(),
        unreadCount: {}
      }, { merge: true });
    }
  }

  const msgRef = collection(db, "conversations", conversationId, "messages");
  await addDoc(msgRef, { 
    senderId, 
    senderName, 
    text, 
    timestamp: serverTimestamp(), 
    readBy: [senderId],
    readAt: { [senderId]: serverTimestamp() }
  });

  // Increment unread count for all other participants
  const currentConv = await getDoc(convRef);
  if (currentConv.exists()) {
    const data = currentConv.data() as ConversationData;
    const updates: Record<string, any> = {
      lastMessage: text,
      lastMessageSenderId: senderId,
      updatedAt: serverTimestamp(),
    };
    
    data.participants.forEach(p => {
      if (p !== senderId) {
        updates[`unreadCount.${p}`] = increment(1);
      }
    });
    
    await updateDoc(convRef, updates);
  }
}

export async function createOrGetDirectConversation(
  uid1: string,
  uid2: string,
  names: Record<string, string>,
  photos: Record<string, string> = {}
): Promise<{ id: string; isNew: boolean; data: Partial<ConversationData> }> {
  const convId = [uid1, uid2].sort().join("_");
  const convRef = doc(db, "conversations", convId);
  const snap = await getDoc(convRef);
  
  const data: Partial<ConversationData> = {
    participants: [uid1, uid2],
    participantNames: names,
    participantPhotos: photos,
    type: "direct",
    lastMessage: "",
    lastMessageSenderId: "",
    unreadCount: { [uid1]: 0, [uid2]: 0 },
  };

  return { id: convId, isNew: !snap.exists(), data };
}

export async function markConversationRead(conversationId: string, uid: string): Promise<void> {
  const convRef = doc(db, "conversations", conversationId);
  await updateDoc(convRef, {
    [`unreadCount.${uid}`]: 0,
  });

  // Batch update messages where user is not in readBy
  const msgsRef = collection(db, "conversations", conversationId, "messages");
  // Firestore doesn't support "NOT IN array", so we just query all recent messages
  // and filter locally for a batch write.
  const q = query(msgsRef, orderBy("timestamp", "desc"), limit(50));
  const snap = await getDocs(q);
  
  const batch = writeBatch(db);
  let batchCount = 0;
  
  snap.docs.forEach(docSnap => {
    const data = docSnap.data();
    if (data.senderId !== uid && (!data.readBy || !data.readBy.includes(uid))) {
      batch.update(docSnap.ref, {
        readBy: arrayUnion(uid),
        [`readAt.${uid}`]: serverTimestamp()
      });
      batchCount++;
    }
  });
  
  if (batchCount > 0) {
    await batch.commit();
  }
}

// --- Group Messaging Methods ---

export async function createGroupConversation(
  creatorUid: string,
  groupName: string,
  participantUids: string[],
  names: Record<string, string>,
  photos: Record<string, string> = {},
  opts?: { eventId?: string, committeeId?: string, groupDescription?: string, groupPhotoUrl?: string, autoGenerated?: boolean }
): Promise<string> {
  const allParticipants = Array.from(new Set([creatorUid, ...participantUids]));
  
  const convData: Partial<ConversationData> = {
    type: "group",
    groupName,
    participants: allParticipants,
    participantNames: names,
    participantPhotos: photos,
    createdBy: creatorUid,
    createdAt: serverTimestamp() as Timestamp,
    admins: [creatorUid],
    unreadCount: allParticipants.reduce((acc, uid) => ({ ...acc, [uid]: 0 }), {}),
    lastMessage: "Group created",
    lastMessageSenderId: "system",
    updatedAt: serverTimestamp() as Timestamp,
    ...opts
  };

  const convRef = await addDoc(collection(db, "conversations"), convData);
  
  await addDoc(collection(db, "conversations", convRef.id, "messages"), {
    senderId: "system",
    senderName: "System",
    text: "Group created",
    timestamp: serverTimestamp(),
    readBy: [creatorUid],
    readAt: { [creatorUid]: serverTimestamp() },
    systemMessage: true
  });
  
  return convRef.id;
}

export async function addGroupMember(
  convId: string, actorUid: string, actorName: string, newUid: string, newName: string, newPhoto: string
): Promise<void> {
  const convRef = doc(db, "conversations", convId);
  await updateDoc(convRef, {
    participants: arrayUnion(newUid),
    [`participantNames.${newUid}`]: newName,
    [`participantPhotos.${newUid}`]: newPhoto,
    [`unreadCount.${newUid}`]: 0,
    lastMessage: `${actorName} added ${newName}`,
    lastMessageSenderId: "system",
    updatedAt: serverTimestamp()
  });
  
  await addDoc(collection(db, "conversations", convId, "messages"), {
    senderId: "system",
    senderName: "System",
    text: `${actorName} added ${newName}`,
    timestamp: serverTimestamp(),
    readBy: [],
    systemMessage: true
  });
}

export async function removeGroupMember(
  convId: string, actorName: string, targetUid: string, targetName: string
): Promise<void> {
  const convRef = doc(db, "conversations", convId);
  const snap = await getDoc(convRef);
  if (!snap.exists()) return;
  
  const data = snap.data() as ConversationData;
  const newParticipants = data.participants.filter(p => p !== targetUid);
  
  await updateDoc(convRef, {
    participants: newParticipants,
    lastMessage: `${actorName} removed ${targetName}`,
    lastMessageSenderId: "system",
    updatedAt: serverTimestamp()
  });
  
  await addDoc(collection(db, "conversations", convId, "messages"), {
    senderId: "system",
    senderName: "System",
    text: actorName === targetName ? `${targetName} left the group` : `${actorName} removed ${targetName}`,
    timestamp: serverTimestamp(),
    readBy: [],
    systemMessage: true
  });
}

export async function updateGroupMeta(
  convId: string, actorUid: string, meta: { groupName?: string, groupPhotoUrl?: string, groupDescription?: string }
): Promise<void> {
  const convRef = doc(db, "conversations", convId);
  await updateDoc(convRef, meta);
}
